/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DiagnosisResult {
  'pesticideRecommendations' : Array<string>,
  'fertilizerRecommendations' : Array<string>,
  'plantName' : string,
  'healthStatus' : HealthStatus,
  'timestamp' : Time,
  'conditions' : Array<string>,
  'image' : [] | [ExternalBlob],
  'careTips' : Array<string>,
}
export type ExternalBlob = Uint8Array;
export type HealthStatus = { 'mild' : null } |
  { 'healthy' : null } |
  { 'severe' : null } |
  { 'moderate' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithDiagnoses {
  'user' : Principal,
  'diagnoses' : Array<DiagnosisResult>,
  'profile' : [] | [UserProfile],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDiagnosis' : ActorMethod<
    [
      string,
      HealthStatus,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'analyzePlantImage' : ActorMethod<[ExternalBlob], DiagnosisResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearDiagnosisHistory' : ActorMethod<[Principal], undefined>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllUsersDiagnoses' : ActorMethod<[], Array<UserWithDiagnoses>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDiagnosisHistory' : ActorMethod<[Principal], Array<DiagnosisResult>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];